import React, { useState, useEffect } from "react"

/* ═══════════════════════════════════════════════════════════════════════════
   828 CONTACT FORM v4.2 - Custom React form → HubSpot Forms API
   ─────────────────────────────────────────────────────────────────────────
   Posts directly to:
     https://api.hsforms.com/submissions/v3/integration/submit/{portal}/{form}

   No iframe, no embed widget - our own DOM, fully brand-styled.
   The HubSpot endpoint accepts the submission anonymously (no auth needed)
   and the lead lands in the CRM exactly as if it came through the embed.

   ANTI-SPAM (two layers):
   1. Honeypot field (invisible). Bots auto-fill all fields including the
      hidden one; we silently reject if it has any value.
   2. Google reCAPTCHA v3 invisible. Generates a fraud score (0.0-1.0) on
      submit and attaches it to the lead as a custom field. Score < 0.5
      typically means bot; Mannie can filter those in HubSpot views.
      (We do NOT block submits client-side - Google explicitly recommends
       NOT to, since attackers can read the threshold. Filtering happens
       in HubSpot or via WP server-side validation in a future iteration.)

   Field mapping confirmed with Manuel Luna (May 2026):
     - Standard properties:  firstname, lastname, company, phone, email,
                             website, city, message
     - Custom properties:    service_interest, biggest_growth_challenge,
                             growth_challenge__other

   CHANGE (June 2026): `annual_revenue_range` and `state` removed. Manuel
   pruned both from the HubSpot form after a lead analysis showed prospects
   were dropping off the form on those two fields. The React form below now
   matches the live HubSpot form exactly.

   CHANGE (Aug 2026) — AD ATTRIBUTION: the form was creating leads with no
   trace of the campaign that produced them. Two additions:
     a) UTM params are read from the URL on mount and cached in
        sessionStorage, so they survive the landing → /contact navigation.
        On submit they are sent as explicit contact properties.
     b) The HubSpot tracking cookie (`hubspotutk`) is sent as `context.hutk`,
        which is what lets HubSpot stitch the submission to the visitor's
        session and original source.

   ⚠ TWO PREREQUISITES OUTSIDE THIS FILE — without them the code runs but
     the data does not land:
     1. The HubSpot tracking code must be installed site-wide (wp_head).
        Until then `hubspotutk` never exists and `hutk` is simply omitted.
     2. The properties utm_source / utm_medium / utm_campaign / utm_content /
        utm_id must exist in the HubSpot portal AND be added to this form.
        HubSpot returns HTTP 400 for unknown field names — the exact failure
        mode we hit before with disallowed `context` keys.
   ═══════════════════════════════════════════════════════════════════════════ */

// ─── HubSpot config ──────────────────────────────────────────────────────
const HS_PORTAL_ID = "245142821"
const HS_FORM_ID   = "f5c11a5a-02e9-4c74-a026-186c2ca036ee"
const HS_SUBMIT_URL = `https://api.hsforms.com/submissions/v3/integration/submit/${HS_PORTAL_ID}/${HS_FORM_ID}`

// ─── Google reCAPTCHA v3 config ──────────────────────────────────────────
// Site key generated by Manuel at https://www.google.com/recaptcha/admin
// (Type: reCAPTCHA v3 INVISIBLE - NOT v2)
// This key is PUBLIC - safe to commit. The matching SECRET key never appears
// here; it would only be needed for server-side verification (future step).
const RECAPTCHA_SITE_KEY = "6LcLuPksAAAAAIkNHnaGokVVZ3JUVpjG935eF4Q5"

// ─── UTM capture config ──────────────────────────────────────────────────
// Each key here must match a HubSpot contact property name EXACTLY.
// `utm_term` is intentionally left out: it is only useful for Search
// campaigns and the property does not exist in the portal yet. Add it to
// this array ONLY after creating it in HubSpot and adding it to the form.
const UTM_KEYS = ["utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_id"]
const UTM_STORAGE_KEY = "828_utm_params"

// Reads UTMs off the current URL and caches them for the rest of the session.
// Why sessionStorage: the ad lands the visitor on the home page or a service
// page, but they submit from /contact. Without caching, the params are gone
// by the time the form is posted and every lead looks like direct traffic.
function captureUtmParams() {
  if (typeof window === "undefined") return

  const params = new URLSearchParams(window.location.search)
  const found = {}

  UTM_KEYS.forEach((key) => {
    const value = params.get(key)
    if (value) found[key] = value
  })

  // Only overwrite when this pageview actually carries UTMs, so an internal
  // navigation without params doesn't wipe the original attribution.
  if (Object.keys(found).length > 0) {
    try {
      sessionStorage.setItem(UTM_STORAGE_KEY, JSON.stringify(found))
    } catch {
      // Private mode / storage disabled — attribution is lost but the form
      // must keep working. Never let this throw into the render path.
    }
  }
}

function getStoredUtmParams() {
  if (typeof window === "undefined") return {}
  try {
    const raw = sessionStorage.getItem(UTM_STORAGE_KEY)
    return raw ? JSON.parse(raw) : {}
  } catch {
    return {}
  }
}

// Reads the HubSpot tracking cookie. Anchored to a cookie boundary so a
// different cookie whose name merely ends in "hubspotutk" can't match.
// Returns "" when the tracking code isn't installed yet.
function getHubspotCookie() {
  if (typeof document === "undefined") return ""
  const match = document.cookie.match(/(?:^|;\s*)hubspotutk=([^;]+)/)
  return match ? match[1] : ""
}

// ─── Meta (Facebook) Pixel — Lead conversion event ───────────────────────
// The pixel base code (installed site-wide via WP Code) only fires PageView.
// Without this call Meta sees the traffic but never learns which visits
// turned into a lead, so campaign optimization has nothing to optimize on.
//
// `fbq` is defined by the base code. We check for it every time instead of
// assuming: the script is third-party and can be blocked by an ad blocker,
// a consent tool, or a network failure. A missing pixel must never break a
// real form submission — the lead is worth more than the analytics event.
function trackMetaLead() {
  if (typeof window === "undefined") return
  if (typeof window.fbq !== "function") return

  try {
    window.fbq("track", "Lead")
  } catch {
    // Swallow: analytics must never surface as an error to the visitor.
  }
}

// ─── reCAPTCHA loader ────────────────────────────────────────────────────
// Module-level promise so multiple ContactForm instances on the same page
// share a single script load instead of racing each other.
let recaptchaLoader = null

function loadRecaptcha() {
  if (recaptchaLoader) return recaptchaLoader

  recaptchaLoader = new Promise((resolve, reject) => {
    // Skip if no real key configured (dev / staging)
    if (!RECAPTCHA_SITE_KEY || RECAPTCHA_SITE_KEY.startsWith("PASTE_")) {
      console.warn("[ContactForm] reCAPTCHA site key not configured. Submitting without token.")
      resolve(null)
      return
    }

    // Already loaded?
    if (typeof window !== "undefined" && window.grecaptcha && window.grecaptcha.ready) {
      window.grecaptcha.ready(() => resolve(window.grecaptcha))
      return
    }

    const scriptSrc = `https://www.google.com/recaptcha/api.js?render=${encodeURIComponent(RECAPTCHA_SITE_KEY)}`
    const existing = document.querySelector(`script[src="${scriptSrc}"]`)
    if (existing) {
      existing.addEventListener("load",  () => window.grecaptcha.ready(() => resolve(window.grecaptcha)))
      existing.addEventListener("error", () => reject(new Error("reCAPTCHA script failed to load")))
      return
    }

    const script = document.createElement("script")
    script.src   = scriptSrc
    script.defer = true
    script.async = true
    script.onload  = () => window.grecaptcha.ready(() => resolve(window.grecaptcha))
    script.onerror = () => reject(new Error("reCAPTCHA script failed to load"))
    document.body.appendChild(script)
  })

  return recaptchaLoader
}

async function getRecaptchaToken(action = "contact_form_submit") {
  try {
    const grecaptcha = await loadRecaptcha()
    if (!grecaptcha) return ""
    return await grecaptcha.execute(RECAPTCHA_SITE_KEY, { action })
  } catch (err) {
    console.warn("[ContactForm] reCAPTCHA token generation failed:", err)
    return "" // fail-open: don't block submit if Google's API is down
  }
}

// ─── Field option lists (values must match HubSpot exactly - Manuel-confirmed) ──
const SERVICE_INTERESTS = [
  "Industry Report",
  "Website Development & SEO",
  "Social Media Management",
  "Paid Advertisement",
  "Brand Identity & Positioning",
  "Pitch Deck & Capabilities Development",
]

const GROWTH_CHALLENGES = [
  "Not enough leads coming in",
  "Customers don't know who we are",
  "Can't compete with bigger companies in our market",
  "Marketing feels expensive but unclear",
  "Other",
]

// ─── Validation helpers ──────────────────────────────────────────────────
const validateEmail = (v) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.trim())
const validatePhone = (v) => {
  const digits = v.replace(/\D/g, "")
  return digits.length >= 7 && digits.length <= 15
}
const validateUrl = (v) => {
  if (!v.trim()) return true // optional
  try { new URL(v.startsWith("http") ? v : `https://${v}`); return true }
  catch { return false }
}

// ─── Reusable bits ───────────────────────────────────────────────────────
const inputClass =
  "w-full bg-white text-[var(--color-midnight-logic)] border border-[rgba(26,28,41,0.15)] rounded-sm px-3 py-2 text-[13px] font-body placeholder:text-[rgba(26,28,41,0.35)] focus:outline-none focus:border-[var(--color-midnight-logic)] focus:ring-[3px] focus:ring-[rgba(163,203,55,0.18)] transition-colors"

function Field({ label, required, error, children }) {
  return (
    <div>
      <label className="block text-[10px] font-body font-medium uppercase tracking-[0.12em] text-[var(--color-midnight-logic)]/75 mb-1">
        {label}
        {required && <span className="text-[var(--color-growth-signal)] ml-1">*</span>}
      </label>
      {children}
      {error && <p className="mt-1 text-[11px] text-red-600 font-medium">{error}</p>}
    </div>
  )
}

// ─── Main component ──────────────────────────────────────────────────────
function ContactForm() {
  const [form, setForm] = useState({
    firstname:                 "",
    lastname:                  "",
    company:                   "",
    phone:                     "",
    email:                     "",
    website:                   "",
    service_interest:          "",
    city:                      "",
    biggest_growth_challenge:  [],
    growth_challenge__other:   "",
    message:                   "",
    consent:                   false,
    // Honeypot - must stay empty. Bots auto-fill it; we reject if filled.
    website_url_backup:        "",
  })
  const [errors, setErrors] = useState({})
  const [status, setStatus] = useState("idle") // idle | submitting | success | error
  const [errorMsg, setErrorMsg] = useState("")

  const update = (key, value) => {
    setForm((f) => ({ ...f, [key]: value }))
    if (errors[key]) setErrors((e) => ({ ...e, [key]: undefined }))
  }

  // Preload reCAPTCHA script on mount so the first submit is instant.
  // Without this preload there's a ~500ms delay the first time the user clicks Submit.
  useEffect(() => {
    loadRecaptcha().catch(() => { /* silently fail; submit will retry */ })
  }, [])

  // Capture ad attribution as early as possible in the session.
  useEffect(() => {
    captureUtmParams()
  }, [])

  const isSubmitting = status === "submitting"

  // ─── Validation ───────────────────────────────────────────────────
  const validate = () => {
    const e = {}
    if (!form.firstname.trim())  e.firstname = "First name is required"
    if (!form.lastname.trim())   e.lastname  = "Last name is required"
    if (!form.company.trim())    e.company   = "Company name is required"

    if (!form.phone.trim())             e.phone = "Phone is required"
    else if (!validatePhone(form.phone)) e.phone = "Enter a valid phone number"

    if (!form.email.trim())             e.email = "Email is required"
    else if (!validateEmail(form.email)) e.email = "Enter a valid email address"

    if (!validateUrl(form.website))     e.website = "Enter a valid URL"

    if (!form.service_interest)          e.service_interest = "Select a service interest"
    if (!form.city.trim())               e.city  = "City is required"

    if (!form.biggest_growth_challenge.length) {
      e.biggest_growth_challenge = "Select at least one"
    } else if (
      form.biggest_growth_challenge.includes("Other") &&
      !form.growth_challenge__other.trim()
    ) {
      e.growth_challenge__other = "Tell us what your challenge is"
    }

    if (!form.message.trim()) e.message = "Message is required"
    if (!form.consent)        e.consent = "Please acknowledge our Terms and Privacy Policy"

    return e
  }

  // ─── Submit ───────────────────────────────────────────────────────
  const handleSubmit = async (e) => {
    e.preventDefault()
    if (isSubmitting) return

    // Honeypot trap - silently "succeed" so the bot thinks it worked
    if (form.website_url_backup) {
      setStatus("success")
      return
    }

    const validation = validate()
    if (Object.keys(validation).length > 0) {
      setErrors(validation)
      return
    }

    setStatus("submitting")
    setErrorMsg("")

    // ─── Generate reCAPTCHA v3 token (invisible, ~300ms) ────────────
    // Returns "" if no key configured or if Google's API is down.
    // Either way we proceed - fail-open ensures the form still works.
    const recaptchaToken = await getRecaptchaToken("contact_form_submit")

    // ─── Build HubSpot v3 submission payload ─────────────────────
    // HubSpot expects: { fields: [{ objectTypeId?, name, value }, ...] }
    // objectTypeId is REQUIRED for the `company` field because the form is
    // configured to auto-create/associate a Company record. We send two
    // entries for it: one on the Contact (0-1) and one on the Company (0-2)
    // so HubSpot sets the Company's `name` property correctly.
    // Other fields default to Contact (0-1).
    const fields = [
      { objectTypeId: "0-1", name: "firstname",                value: form.firstname.trim() },
      { objectTypeId: "0-1", name: "lastname",                 value: form.lastname.trim()  },
      { objectTypeId: "0-1", name: "company",                  value: form.company.trim()   },
      // Mirror the company name onto the Company object (0-2) under its
      // internal `name` property. HubSpot needs this to create the Company.
      { objectTypeId: "0-2", name: "name",                     value: form.company.trim()   },
      { objectTypeId: "0-1", name: "phone",                    value: form.phone.trim()     },
      { objectTypeId: "0-1", name: "email",                    value: form.email.trim()     },
      { objectTypeId: "0-1", name: "service_interest",         value: form.service_interest },
      { objectTypeId: "0-1", name: "city",                     value: form.city.trim()      },
      // Multi-checkbox: HubSpot expects semicolon-joined string for enumeration
      // properties of type "checkbox" (multi-select)
      { objectTypeId: "0-1", name: "biggest_growth_challenge", value: form.biggest_growth_challenge.join(";") },
      // Message field - HubSpot internal name is `lead_message` (not the standard `message`)
      { objectTypeId: "0-1", name: "lead_message",             value: form.message.trim()   },
    ]

    if (form.website.trim()) {
      fields.push({ objectTypeId: "0-1", name: "website", value: form.website.trim() })
    }
    if (form.biggest_growth_challenge.includes("Other") && form.growth_challenge__other.trim()) {
      fields.push({
        objectTypeId: "0-1",
        name:  "growth_challenge__other",
        value: form.growth_challenge__other.trim(),
      })
    }

    // Consent: HubSpot expects this as a regular boolean checkbox field
    // (not via legalConsentOptions). Internal name: agreed_to_privacy_policy_and_terms
    // Boolean values must be sent as the strings "true" / "false".
    fields.push({
      objectTypeId: "0-1",
      name:  "agreed_to_privacy_policy_and_terms",
      value: form.consent ? "true" : "false",
    })

    // ─── Ad attribution: UTMs cached earlier in the session ──────────
    // Only keys that actually have a value get pushed, so an organic visit
    // never sends empty utm_* properties and overwrite good data.
    const utmParams = getStoredUtmParams()
    Object.entries(utmParams).forEach(([key, value]) => {
      if (UTM_KEYS.includes(key) && value) {
        fields.push({ objectTypeId: "0-1", name: key, value })
      }
    })

    // ─── Context ────────────────────────────────────────────────────
    // HubSpot only accepts a closed list of keys here and 400s on anything
    // else — including, in practice, an empty `hutk`. So the cookie is added
    // conditionally: present once the tracking code is installed, absent
    // (and harmless) until then.
    const context = {
      pageUri:   typeof window !== "undefined" ? window.location.href     : "",
      pageName:  typeof document !== "undefined" ? document.title         : "",
    }

    const hutk = getHubspotCookie()
    if (hutk) context.hutk = hutk

    const payload = { fields, context }

    // Note on reCAPTCHA: we still generate `recaptchaToken` above (kept for
    // server-side validation if/when we add the WP handler), but we don't
    // attach it to the HubSpot payload. HubSpot v3 only accepts a closed
    // list of fields under `context` and rejects unknown ones with HTTP 400.
    // Google still tracks the score for our own monitoring at:
    //   https://www.google.com/recaptcha/admin
    // The score is visible per-day there even without server-side check.
    void recaptchaToken

    // NOTE: the debug payload dump that lived here was removed once UTM
    // attribution was verified in production (Aug 2026). It printed every
    // lead's email and phone into the browser console on the live site.
    // If you need it again, re-add it temporarily and strip it before deploy.

    try {
      const res = await fetch(HS_SUBMIT_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      })

      if (!res.ok) {
        const errBody = await res.json().catch(() => null)
        console.error("[ContactForm] HubSpot rejected submission:", res.status, errBody)
        // HubSpot returns { status, errors: [{ errorType, message }, ...] }
        // Log every error individually so debugging is fast (multiple field
        // issues can come back in a single 400 response).
        if (errBody?.errors && Array.isArray(errBody.errors)) {
          errBody.errors.forEach((e, i) => {
            console.error(`[ContactForm] HubSpot error ${i + 1}/${errBody.errors.length}:`, e.message || e)
          })
        }
        const allMessages = errBody?.errors?.map((e) => e.message).filter(Boolean).join(" · ")
        throw new Error(allMessages || errBody?.message || `HubSpot returned ${res.status}`)
      }

      // Fire the Meta conversion only after HubSpot confirms the lead was
      // accepted. Firing it before the response (or on validation failure)
      // would inflate the conversion count and skew campaign optimization.
      trackMetaLead()

      setStatus("success")
    } catch (err) {
      console.error("[ContactForm] Submit error:", err)
      setStatus("error")
      setErrorMsg(err.message || "Something went wrong. Please try again or email us directly.")
    }
  }

  // ─── Success state ────────────────────────────────────────────────
  if (status === "success") {
    return (
      <div className="bg-white border border-[var(--color-growth-signal)] rounded-md p-8 lg:p-10 shadow-[0_12px_32px_-8px_rgba(26,28,41,0.15)]">
        <div className="flex items-center justify-center w-12 h-12 rounded-full bg-[var(--color-growth-signal)]/15 mb-5">
          <svg className="w-6 h-6 text-[var(--color-growth-signal)]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <polyline points="20 6 9 17 4 12" />
          </svg>
        </div>
        <h3 className="font-display font-bold text-xl lg:text-2xl text-[var(--color-midnight-logic)] mb-2">
          We received your message.
        </h3>
        <p className="text-sm text-[var(--color-metric-steel)] leading-relaxed max-w-md">
          One of us will reach out within one business day to walk you through what the market is actually seeing about your business - and what to do about it.
        </p>
      </div>
    )
  }

  // ─── Form ─────────────────────────────────────────────────────────
  const challengeIncludesOther = form.biggest_growth_challenge.includes("Other")

  return (
    <form
      onSubmit={handleSubmit}
      noValidate
      className="bg-white rounded-md p-5 lg:p-6 shadow-[0_12px_32px_-8px_rgba(26,28,41,0.15),0_4px_8px_-4px_rgba(26,28,41,0.06)]"
    >
      <p className="text-[13px] text-[var(--color-metric-steel)] leading-snug mb-5">
        Thanks for reaching out. We'll review your message and get back to you within 1 business day. <span className="text-[var(--color-midnight-logic)] font-medium">- The 828 Marketing Solutions Team</span>
      </p>

      {/* Honeypot - invisible to humans, bots fill it */}
      <div aria-hidden="true" style={{ position: "absolute", left: "-9999px", opacity: 0, height: 0, overflow: "hidden" }}>
        <label>
          Website URL (do not fill)
          <input
            type="text"
            tabIndex="-1"
            autoComplete="off"
            value={form.website_url_backup}
            onChange={(e) => update("website_url_backup", e.target.value)}
          />
        </label>
      </div>

      {/* Grid: 2 cols for short fields, full row for long ones */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-3 gap-y-3">

        <Field label="First Name" required error={errors.firstname}>
          <input
            type="text"
            value={form.firstname}
            onChange={(e) => update("firstname", e.target.value)}
            className={inputClass}
            disabled={isSubmitting}
            autoComplete="given-name"
          />
        </Field>

        <Field label="Last Name" required error={errors.lastname}>
          <input
            type="text"
            value={form.lastname}
            onChange={(e) => update("lastname", e.target.value)}
            className={inputClass}
            disabled={isSubmitting}
            autoComplete="family-name"
          />
        </Field>

        <Field label="Company Name" required error={errors.company}>
          <input
            type="text"
            value={form.company}
            onChange={(e) => update("company", e.target.value)}
            className={inputClass}
            disabled={isSubmitting}
            autoComplete="organization"
          />
        </Field>

        <Field label="Phone" required error={errors.phone}>
          <input
            type="tel"
            value={form.phone}
            onChange={(e) => update("phone", e.target.value)}
            className={inputClass}
            placeholder="(555) 123-4567"
            disabled={isSubmitting}
            autoComplete="tel"
          />
        </Field>

        <Field label="Email" required error={errors.email}>
          <input
            type="email"
            value={form.email}
            onChange={(e) => update("email", e.target.value)}
            className={inputClass}
            placeholder="you@business.com"
            disabled={isSubmitting}
            autoComplete="email"
          />
        </Field>

        <Field label="Website URL" error={errors.website}>
          <input
            type="text"
            value={form.website}
            onChange={(e) => update("website", e.target.value)}
            className={inputClass}
            placeholder="yourbusiness.com"
            disabled={isSubmitting}
            autoComplete="url"
          />
        </Field>

        <Field label="Service Interest" required error={errors.service_interest}>
          <SelectInput
            value={form.service_interest}
            onChange={(v) => update("service_interest", v)}
            options={SERVICE_INTERESTS}
            disabled={isSubmitting}
            placeholder="Select…"
          />
        </Field>

        <Field label="City" required error={errors.city}>
          <input
            type="text"
            value={form.city}
            onChange={(e) => update("city", e.target.value)}
            className={inputClass}
            disabled={isSubmitting}
            autoComplete="address-level2"
          />
        </Field>
      </div>

      {/* Growth Challenge - full width */}
      <div className="mt-4">
        <label className="block text-[10px] font-body font-medium uppercase tracking-[0.12em] text-[var(--color-midnight-logic)]/75 mb-0.5">
          What's your biggest growth challenge right now?
          <span className="text-[var(--color-growth-signal)] ml-1">*</span>
        </label>
        <p className="text-[10px] text-[var(--color-metric-steel)] italic mb-2">Select all that apply.</p>

        <div className="grid grid-cols-1 gap-1.5">
          {GROWTH_CHALLENGES.map((opt) => {
            const selected = form.biggest_growth_challenge.includes(opt)
            const toggle = () => {
              const next = selected
                ? form.biggest_growth_challenge.filter((v) => v !== opt)
                : [...form.biggest_growth_challenge, opt]
              update("biggest_growth_challenge", next)
              if (opt === "Other" && selected) update("growth_challenge__other", "")
            }
            return (
              <label
                key={opt}
                className={`flex items-start gap-2.5 px-3 py-2 rounded-sm border cursor-pointer transition-colors duration-150 ${
                  selected
                    ? "border-[var(--color-midnight-logic)] bg-[var(--color-midnight-logic)]/[0.03]"
                    : "border-[rgba(26,28,41,0.15)] hover:border-[rgba(26,28,41,0.4)]"
                }`}
              >
                <input
                  type="checkbox"
                  checked={selected}
                  onChange={toggle}
                  disabled={isSubmitting}
                  className="sr-only"
                />
                <span
                  className={`flex items-center justify-center w-4 h-4 rounded-sm border-2 shrink-0 mt-0.5 transition-colors duration-150 ${
                    selected
                      ? "border-[var(--color-growth-signal)] bg-[var(--color-growth-signal)]"
                      : "border-[rgba(26,28,41,0.3)]"
                  }`}
                  aria-hidden="true"
                >
                  {selected && (
                    <svg className="w-2.5 h-2.5 text-[var(--color-midnight-logic)]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round">
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                  )}
                </span>
                <span className="text-[13px] font-medium text-[var(--color-midnight-logic)] leading-snug">
                  {opt}
                </span>
              </label>
            )
          })}
        </div>
        {errors.biggest_growth_challenge && (
          <p className="mt-1 text-[11px] text-red-600 font-medium">{errors.biggest_growth_challenge}</p>
        )}

        {/* Conditional "Other" textarea */}
        {challengeIncludesOther && (
          <div className="mt-3">
            <textarea
              value={form.growth_challenge__other}
              onChange={(e) => update("growth_challenge__other", e.target.value)}
              disabled={isSubmitting}
              rows={2}
              placeholder="Describe your biggest growth challenge in your own words…"
              className={`${inputClass} resize-none`}
              maxLength={500}
            />
            {errors.growth_challenge__other && (
              <p className="mt-1 text-[11px] text-red-600 font-medium">{errors.growth_challenge__other}</p>
            )}
            <p className="mt-0.5 text-[10px] text-[var(--color-metric-steel)]/70 text-right">
              {form.growth_challenge__other.length}/500
            </p>
          </div>
        )}
      </div>

      {/* Message textarea */}
      <div className="mt-4">
        <Field label="Message" required error={errors.message}>
          <textarea
            value={form.message}
            onChange={(e) => update("message", e.target.value)}
            disabled={isSubmitting}
            rows={3}
            placeholder="Tell us what you're working on. We'll get back within one business day."
            className={`${inputClass} resize-none`}
            maxLength={2000}
          />
        </Field>
      </div>

      {/* Consent */}
      <div className="mt-4 pt-4 border-t border-[rgba(26,28,41,0.08)]">
        <label className="flex items-start gap-2.5 cursor-pointer">
          <input
            type="checkbox"
            checked={form.consent}
            onChange={(e) => update("consent", e.target.checked)}
            disabled={isSubmitting}
            className="mt-0.5 w-4 h-4 rounded-sm cursor-pointer"
            style={{ accentColor: "var(--color-growth-signal)" }}
          />
          <span className="text-[11px] text-[var(--color-metric-steel)] leading-snug">
            I agree to 828 Marketing Solutions'{" "}
            <a href="/terms-conditions" target="_blank" rel="noopener noreferrer" className="text-[var(--color-midnight-logic)] font-medium underline hover:text-[var(--color-growth-signal)] transition-colors">
              Terms &amp; Conditions
            </a>{" "}
            and{" "}
            <a href="/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-[var(--color-midnight-logic)] font-medium underline hover:text-[var(--color-growth-signal)] transition-colors">
              Privacy Policy
            </a>.
          </span>
        </label>
        {errors.consent && (
          <p className="mt-1 text-[11px] text-red-600 font-medium">{errors.consent}</p>
        )}
      </div>

      {/* Error banner (server errors) */}
      {status === "error" && errorMsg && (
        <div className="mt-4 px-4 py-3 bg-red-50 border border-red-200 rounded-sm">
          <p className="text-[12px] text-red-700 font-medium leading-snug">{errorMsg}</p>
        </div>
      )}

      {/* Submit + reCAPTCHA disclaimer */}
      <div className="mt-5 flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4">
        {/* Google reCAPTCHA disclaimer - REQUIRED by Google ToS when hiding the badge.
            See: https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge */}
        <p className="text-[10px] text-[var(--color-metric-steel)]/65 leading-snug max-w-xs">
          Protected by reCAPTCHA. Google's{" "}
          <a
            href="https://policies.google.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-[var(--color-growth-signal)] transition-colors"
          >
            Privacy Policy
          </a>{" "}
          and{" "}
          <a
            href="https://policies.google.com/terms"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-[var(--color-growth-signal)] transition-colors"
          >
            Terms of Service
          </a>{" "}
          apply.
        </p>

        <button
          type="submit"
          disabled={isSubmitting}
          className="group inline-flex items-center gap-2 bg-[var(--color-growth-signal)] text-[var(--color-midnight-logic)] px-6 py-3 rounded-sm font-body font-medium text-[13px] uppercase tracking-[0.05em] hover:brightness-95 disabled:opacity-55 disabled:cursor-not-allowed transition-all duration-200 min-w-[180px] justify-center"
        >
          {isSubmitting ? (
            <>
              <svg className="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                <path d="M21 12a9 9 0 1 1-6.219-8.56" strokeLinecap="round" />
              </svg>
              Sending…
            </>
          ) : (
            <>
              Submit
              <svg className="w-4 h-4 transform transition-transform duration-200 group-hover:translate-x-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <line x1="5" y1="12" x2="19" y2="12" /><polyline points="12 5 19 12 12 19" />
              </svg>
            </>
          )}
        </button>
      </div>
    </form>
  )
}

// ─── Custom select with brand dropdown arrow ─────────────────────────────
function SelectInput({ value, onChange, options, disabled, placeholder }) {
  return (
    <div className="relative">
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        className={`${inputClass} pr-9 cursor-pointer appearance-none bg-no-repeat`}
      >
        <option value="" disabled>{placeholder || "Select…"}</option>
        {options.map((opt) => (
          <option key={opt} value={opt}>{opt}</option>
        ))}
      </select>
      {/* Custom dropdown arrow */}
      <svg
        className="absolute right-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-[var(--color-midnight-logic)] pointer-events-none"
        viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"
      >
        <polyline points="6 9 12 15 18 9" />
      </svg>
    </div>
  )
}

export default ContactForm